### ISSUE TITLE
Runtime crash with redux-kotlin 0.5.1

### ISSUE THREAD

**Issue by patricebelisle** [reduxkotlin/presenter-middleware#3]
Problem : Runtime crash
Reproducibility  : 100%

How to get the problem:  Issue can be replicated using the name-game sample demo by replacing the redux version from 0.2.6 to 0.5.1. 

Stacktrace:

2020-07-02 15:34:05.816 30944-30944/org.reduxkotlin.namegame E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.reduxkotlin.namegame, PID: 30944
    java.lang.IncompatibleClassChangeError: Found interface org.reduxkotlin.Store, but class was expected (declaration of 'org.reduxkotlin.Store' appears in /data/app/org.reduxkotlin.namegame-g1Miez194nripwwwguv9zA==/base.apk!classes3.dex)
        at org.reduxkotlin.PresenterMiddlewareKt$presenterEnhancer$1$1.invoke(PresenterMiddleware.kt:48)
        at org.reduxkotlin.PresenterMiddlewareKt$presenterEnhancer$1$1.invoke(Unknown Source:2)
        at org.reduxkotlin.CreateStoreKt.createStore(CreateStore.kt:43)
        at org.reduxkotlin.namegame.common.GameEngine.<init>(GameEngine.kt:23)
        at org.reduxkotlin.namegame.NameGameApp.onCreate(NameGameApp.kt:21)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1165)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6039)
        at android.app.ActivityThread.access$1300(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by melbic** [comment]
@patricebelisle As a workaround you can copy the src files of this package directly into your source.

**Comment by patjackson52** [comment]
@patricebelisle Thanks for reporting.  I'm targeting first & second week in August to give this lib some TLC.

**Comment by shyamvala** [comment]
Hi, Just curious if there has been any traction on this. if not i will try the suggestion from Melbic.

thank you
